import { createLogger } from '../../../shared/logger';
import type { AiProviderChain } from '../../../infrastructure/ai/ai-provider-chain';

const logger = createLogger('homeopathy-prescription-engine');

export interface GnmAnalysis {
  coreConflict: {
    conflictType: string;
    affectedTissue: string;
    biologicalMeaning: string;
    triggerEvents: string[];
  };
  phases: {
    conflictActive: string;
    healingPhase: string;
    isRecurrentTrack: boolean;
    trackTriggers: string[];
  };
  homeopathicTotality: {
    mentalEmotional: string[];
    physicalGenerals: string[];
  };
  emotionalIntensities?: Array<{
    emotion: string;
    intensity: number;
  }>;
  rankedRemedies: Array<{
    rank: number;
    name: string;
    matchStrength: 'strongest' | 'strong' | 'moderate';
    keynotes: string[];
    suggestedPotency: string;
    whenToUse: string;
  }>;
  resolutionStrategy: {
    directions: string[];
    prognosis: string;
  };
  confidence: number;
}

export interface HomeopathyPrescriptionDraft {
  consultationSummary: string; // SYMPTOMS
  diagnosis: string;
  materiaMedicaValidation: string;
  suggestedRemedy: string;
  suggestedRemedies: Array<{
    remedyName: string;
    potency: string;
    dosage: string;
  }>;
  potency: string;
  dosage: string;
  safetyWarnings: string[];
  missingInformation: string[];
  advice: string[];
  followUp: string;
  confidence: number;
  gnmAnalysis?: GnmAnalysis | null;   // GNM interpretation
}

export class HomeopathyPrescriptionEngine {
  constructor(private providerChain: AiProviderChain) {}

  async generatePrescription(
    tenantId: string,
    userId: string,
    input: {
      transcript?: string;
      clinicalData: any;
      diagnosisData: any;
      selectedRubrics: any[];
      remedyScores: any;
    }
  ): Promise<HomeopathyPrescriptionDraft> {
    const topRemedy = input.remedyScores?.scoredRemedies?.[0];
    const otherCandidates = input.remedyScores?.scoredRemedies?.slice(1, 4) || [];

    const systemPrompt = `You are a Master Homeopath and GNM (German New Medicine) Expert.
Your task is to review the candidate remedies generated by the repertorization engine, evaluate them against the patient's raw symptoms, Materia Medica, and the underlying GNM biological conflict, and SELECT the single most accurate remedy.

You must deeply analyze the case. If the mathematically "Top Match" does not fit the patient's actual pathology or diagnosis (e.g., choosing a generic polycrest instead of a specific organ remedy), you MUST override it and select the most appropriate remedy from the "Other Candidates" (or suggest a better one based on Materia Medica).

CORE OUTPUT PRINCIPLES:
1. LEGAL STANDARD: Clinical notes must be professional, legal records.
2. STRICT CONCISENESS: Every field (including advice and GNM) must be EXTREMELY BRIEF bullet points (•). MAX 2 points per field, MAX 10 words per point. NEVER use continuous paragraphs.

GNM (German New Medicine) Rules:
- Identify the core biological conflict based on the affected organ/tissue.
- Explain the biological meaning of the symptom.
- Deduce the trigger events even if not explicitly stated.

Output JSON Format:
{
  "consultationSummary": "• Symptom (duration only if explicitly mentioned)",
  "materiaMedicaValidation": "Explain why the chosen remedy is the best fit based on Materia Medica and GNM.",
  "diagnosis": "Final diagnosis",
  "suggestedRemedy": "Remedy Name (Your final choice)",
  "potency": "e.g., 30C",
  "dosage": "e.g., 2 pills 3 times a day",
  "safetyWarnings": ["red flags"],
  "missingInformation": ["what to ask next"],
  "advice": ["lifestyle advice"],
  "followUp": "timeline",
  "confidence": 0.85,
  "gnmAnalysis": {
    "coreConflict": {
      "conflictType": "(identify or deduce conflict type)",
      "affectedTissue": "(map to correct embryological layer)",
      "biologicalMeaning": "(explain WHY this symptom exists per GNM)",
      "triggerEvents": ["(deduce likely emotional trigger events)"]
    },
    "phases": {
      "conflictActive": "(what happens during active conflict)",
      "healingPhase": "(what healing looks like)",
      "isRecurrentTrack": true,
      "trackTriggers": ["(deduce likely recurring tracks/triggers)"]
    },
    "homeopathicTotality": {
      "mentalEmotional": ["(extract from transcript)"],
      "physicalGenerals": ["(extract from transcript)"]
    },
    "emotionalIntensities": [
      {"emotion":"(emotion)","intensity":80}
    ],
    "rankedRemedies": [
      {"rank":1,"name":"(actual remedy)","matchStrength":"strongest","keynotes":["(real keynotes)"],"suggestedPotency":"(appropriate potency)","whenToUse":"(specific condition for THIS patient)"}
    ],
    "resolutionStrategy": {
      "directions": ["• Short point 1", "• Short point 2"],
      "prognosis": "• EXTREMELY short outcome sentence."
    },
    "confidence": 0.85
  }
}`;

    const userPrompt = `Input Data:
Transcript: ${input.transcript || 'N/A'}
Clinical Symptoms: ${JSON.stringify(input.clinicalData?.observations || [])}
Clinical/Lab Findings: ${JSON.stringify(input.clinicalData?.clinicalFindings || [])}
Mental State: ${JSON.stringify(input.clinicalData?.mentalState || [])}
Provisional Diagnosis: ${input.diagnosisData?.primaryDiagnosis?.name || 'Pending'}

Repertory Engine Output:
- Top Scored Match: ${topRemedy?.remedyName} (Score: ${topRemedy?.totalScore})
- Top Match Keynotes: ${JSON.stringify(topRemedy?.keynotes || [])}
- Other Candidates: ${otherCandidates.map((c: any) => c.remedyName).join(', ')}

Task:
1. Analyze the symptoms using GNM.
2. Confirm the best remedy using Materia Medica. DO NOT blindly trust the Top Scored Match if it is a generic polycrest that doesn't fit the actual diagnosis (e.g., Diabetes, Hypertension, etc.). Select the truest simillimum from the candidates or your own Materia Medica knowledge.
3. Output the final JSON report.`;

    try {
      const response = await this.providerChain.complete({
        systemPrompt,
        userPrompt,
        temperature: 0.2,
        maxTokens: 2048,
        responseFormat: 'json',
      });

      const jsonStr = response.content.substring(response.content.indexOf('{'), response.content.lastIndexOf('}') + 1);
      let parsed = JSON.parse(jsonStr || response.content);
      
      if (!parsed.suggestedRemedies || !Array.isArray(parsed.suggestedRemedies)) {
        parsed.suggestedRemedies = [{
          remedyName: topRemedy?.remedyName || '',
          potency: parsed.potency || '30C',
          dosage: parsed.dosage || '2 pills/day'
        }];
        
        otherCandidates.forEach((c: any) => {
          parsed.suggestedRemedies.push({
            remedyName: c.remedyName,
            potency: '30C',
            dosage: '2 pills/day'
          });
        });
      }

      if (!parsed.suggestedRemedy && topRemedy?.remedyName) {
        parsed.suggestedRemedy = topRemedy.remedyName;
      }

      logger.info({ tenantId, primaryRemedy: parsed.suggestedRemedy, hasGnm: !!parsed.gnmAnalysis }, 'Homeopathy prescription drafted');
      return parsed;

    } catch (error: any) {
      logger.error({ error: error.message }, 'Homeopathy prescription drafting failed');
      return {
        consultationSummary: input.clinicalData?.clinical_summary || 'Symptoms analysis failed.',
        diagnosis: input.diagnosisData?.primaryDiagnosis?.name || 'Pending assessment',
        materiaMedicaValidation: 'Analysis incomplete.',
        suggestedRemedy: topRemedy?.remedyName || 'Consultation required',
        suggestedRemedies: [
          { remedyName: topRemedy?.remedyName || '', potency: '30C', dosage: '2 pills/day' },
          ...otherCandidates.map((c: any) => ({ remedyName: c.remedyName, potency: '30C', dosage: '2 pills/day' }))
        ],
        potency: '30C',
        dosage: '3 doses/day',
        safetyWarnings: ['Please consult your physician for manual review.'],
        missingInformation: [],
        advice: ['Ensure rest and hydration.'],
        followUp: '3 days',
        confidence: 0.1,
        gnmAnalysis: null,
      };
    }
  }
}
