import { pgTable, integer, text, timestamp } from "drizzle-orm/pg-core";

export const appointmentsLegacy = pgTable("appointments", {
  id: integer("id").notNull(),
  clinicId: integer("clinic_id"),
  bookingDate: text("booking_date"),
  bookingTime: text("booking_time"),
  patientId: integer("patient_id"),
  assistantDoctor: text("assistant_doctor"),
  patientName: text("patient_name"),
  address: text("address"),
  state: text("state"),
  city: text("city"),
  phone: text("phone"),
  status: text("status").notNull(),
  createdAt: timestamp("created_at"),
  updatedAt: timestamp("updated_at"),
  deletedAt: text("deleted_at"),
  firstName: text("first_name"),
  lastName: text("last_name"),
  fatherName: text("father_name"),
  age: integer("age"),
  pendingPayment: text("pending_payment"),
  visitType: text("visit_type"),
  notes: text("notes"),
  consultationFee: text("consultation_fee"),
  tokenNo: integer("token_no"),
  durationMinutes: integer("duration_minutes"),
  cancellationReason: text("cancellation_reason"),
});
