import { pgTable, integer, timestamp, text } from "drizzle-orm/pg-core";

export const basicDetailsLegacy = pgTable("basic_details", {
  regid: integer("regid").notNull(),
  id: integer("id").notNull(),
  currentDate: timestamp("current_date").notNull(),
  title: text("title"),
  firstName: text("first_name"),
  middleName: text("middle_name"),
  surname: text("surname"),
  gender: text("gender"),
  religion: text("religion"),
  status: text("status"),
  dateOfBirth: timestamp("date_of_birth").notNull(),
  occupation: text("occupation"),
  address: text("address"),
  courieroutstation: text("courieroutstation"),
  road: text("road"),
  area: text("area"),
  city: text("city"),
  state: text("state"),
  pin: text("pin"),
  phoneNo: integer("phone_no"),
  emailId: text("email_id"),
  mobile1: integer("mobile1"),
  mobile2: integer("mobile2"),
  reference: text("reference"),
  referedBy: text("refered_by"),
  sendSms: text("send_sms"),
  selectScheme: text("select_scheme"),
  endDate: timestamp("end_date"),
  deletedAt: timestamp("deleted_at").notNull(),
  updatedAt: timestamp("updated_at"),
  createdAt: timestamp("created_at"),
});
