import { pgTable, integer, text, timestamp } from "drizzle-orm/pg-core";

export const billLegacy = pgTable("bill", {
  id: integer("id").notNull(),
  regid: integer("regid"),
  randId: text("rand_id"),
  Treatment: text("Treatment"),
  Disease: text("Disease"),
  fromdate: text("fromdate"),
  todate: text("todate"),
  toDate: text("to_date"),
  Rupess: integer("Rupess"),
  BillNo: integer("BillNo"),
  DoctorID: integer("DoctorID"),
  RupeesInAmount: text("RupeesInAmount"),
  Days: text("Days"),
  BillDate: text("BillDate"),
  paymentMode: text("payment_mode"),
  charges: integer("charges"),
  received: integer("received"),
  Balance: integer("Balance"),
  chargeId: integer("charge_id"),
  BalanceInAmount: text("BalanceInAmount"),
  ReceivedInAmount: text("ReceivedInAmount"),
  callStatus: text("call_status"),
  callDate: text("call_date"),
  createdAt: timestamp("created_at"),
  updatedAt: timestamp("updated_at"),
  deletedAt: timestamp("deleted_at"),
});
