import { pgTable, serial, integer, text, date, timestamp } from "drizzle-orm/pg-core";

export const caseDatasLegacy = pgTable("case_datas", {
  id: integer("id").primaryKey(),
  clinicId: integer("clinic_id"),
  regid: integer("regid"),
  patientid: integer("patientid"),
  assitantDoctor: text("assitant_doctor"),
  consultationFee: integer("consultation_fee"),
  dob: date("dob"),
  age: integer("age"),
  title: text("title"),
  firstName: text("first_name"),
  middleName: text("middle_name"),
  surname: text("surname"),
  gender: text("gender"),
  status: text("status"),
  dateOfBirth: text("date_of_birth"),
  address: text("address"),
  road: text("road"),
  religion: text("religion"),
  occupation: text("occupation"),
  altAddress: text("alt_address"),
  phone: text("phone"),
  area: text("area"),
  city: text("city"),
  mobile1: text("mobile1"),
  state: text("state"),
  pin: text("pin"),
  mobile2: text("mobile2"),
  courierOutstation: text("courier_outstation"),
  sendSms: text("send_sms"),
  email: text("email"),
  scheme: text("scheme"),
  image: text("image"),
  deletedAt: timestamp("deleted_at"),
  updatedAt: timestamp("updated_at"),
  createdAt: timestamp("created_at"),
  reference: text("reference"),
  referedName: text("refered_name"),
  referedBy: text("refered_by"),
  abhaId: text("abha_id"),
  coupon: text("coupon").notNull(),
  referedSms: text("refered_sms"),
  sdate: date("sdate"),
  notes: text("notes"),
  bloodGroup: text("blood_group"),
});
