import { pgTable, integer, text, date, real, timestamp } from "drizzle-orm/pg-core";

export const doctorsLegacy = pgTable("doctors", {
  id: integer("id").notNull(),
  clinicId: integer("clinic_id"),
  name: text("name").notNull(),
  password: text("password"),
  title: text("title"),
  firstname: text("firstname"),
  middlename: text("middlename"),
  surname: text("surname"),
  qualification: text("qualification"),
  instutitue: text("instutitue"),
  passedout: text("passedout"),
  permanentaddress: text("permanentaddress"),
  joiningdate: date("joiningdate"),
  registrationId: text("registrationId"),
  aadharnumber: text("aadharnumber"),
  profilepic: text("profilepic"),
  pannumber: text("pannumber"),
  col10Document: text("10_document"),
  col12Document: text("12_document"),
  bhmsDocument: text("bhms_document"),
  mdDocument: text("md_document"),
  registrationCertificate: text("registration_certificate"),
  aadharCard: text("aadhar_card"),
  panCard: text("pan_card"),
  appointmentLetter: text("appointment_letter"),
  designation: text("designation").notNull(),
  gender: text("gender").notNull(),
  mobile: text("mobile").notNull(),
  mobile2: text("mobile2").notNull(),
  email: text("email").notNull(),
  dept: integer("dept").notNull(),
  city: text("city").notNull(),
  address: text("address").notNull(),
  about: text("about").notNull(),
  dateBirth: date("date_birth").notNull(),
  dateLeft: date("date_left").notNull(),
  salaryCur: real("salary_cur").notNull(),
  consultationFee: text("consultation_fee"),
  deletedAt: timestamp("deleted_at"),
  createdAt: timestamp("created_at"),
  updatedAt: timestamp("updated_at"),
});
