import { pgTable, integer, text, date, real, timestamp } from "drizzle-orm/pg-core";

export const medicalcasesLegacy = pgTable("medicalcases", {
  id: integer("id").notNull(),
  clinicId: integer("clinic_id"),
  regid: integer("regid"),
  dob: text("dob"),
  name: text("name"),
  designation: text("designation"),
  gender: text("gender"),
  mobile: text("mobile"),
  mobile2: text("mobile2"),
  doctorname: text("doctorname"),
  dept: integer("dept"),
  city: text("city"),
  address: text("address"),
  altAddress: text("alt_address"),
  about: text("about"),
  dateBirth: text("date_birth"),
  filterDob: date("filter_dob"),
  consultationFee: text("consultation_fee"),
  package: integer("package"),
  packageStart: text("package_start"),
  dateLeft: text("date_left"),
  packageEnddate: text("package_enddate"),
  salaryCur: real("salary_cur"),
  scancase: text("scancase"),
  deletedAt: timestamp("deleted_at"),
  createdAt: timestamp("created_at"),
  updatedAt: timestamp("updated_at"),
});
