import { pgTable, integer, text } from "drizzle-orm/pg-core";

export const tempPersonal12Legacy = pgTable("temp_personal12", {
  ID: integer("ID"),
  RegID: integer("RegID"),
  DoctorID: integer("DoctorID"),
  FamilyID: integer("FamilyID"),
  TitleID: integer("TitleID"),
  Name: text("Name"),
  Surname: text("Surname"),
  Middlename: text("Middlename"),
  DateOfBirth: text("DateOfBirth"),
  Gender: text("Gender"),
  StatusID: integer("StatusID"),
  Address: text("Address"),
  Disease: text("Disease"),
  Constitutional: text("Constitutional"),
  Acute: text("Acute"),
  InterCurrent: text("InterCurrent"),
  OccupationID: integer("OccupationID"),
  ReligionID: integer("ReligionID"),
  Phone: text("Phone"),
  DateOfLastUpdate: text("DateOfLastUpdate"),
  DateOfEntry: text("DateOfEntry"),
  Email: text("Email"),
  SchemeId: text("SchemeId"),
  EndDate: text("EndDate"),
  Mobile1: text("Mobile1"),
  Mobile2: text("Mobile2"),
  SMSAlert: text("SMSAlert"),
  Area: text("Area"),
  City: text("City"),
  State: text("State"),
  PIN: text("PIN"),
  RefID: text("RefID"),
  RefBy: text("RefBy"),
  AssistantDoctorID: integer("AssistantDoctorID"),
  Road: text("Road"),
  PackageID: integer("PackageID"),
  GHPScore: text("GHPScore"),
  Prognosis: text("Prognosis"),
});
