-- Add missing columns to users table (columns referenced by staff creation mirror)
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "title" text;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "firstname" text;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "middlename" text;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "surname" text;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "gender" text DEFAULT 'Male';
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "mobile" text;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "mobile2" text;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "city" text;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "address" text;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "permanent_address" text;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "about" text;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "date_birth" date;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "date_left" date;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "joiningdate" date;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "designation" text;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "dept" integer;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "qualification" text;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "institute" text;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "passed_out" text;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "registration_id" text;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "consultation_fee" real DEFAULT 0;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "salary_cur" real DEFAULT 0;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "aadharnumber" text;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "pannumber" text;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "profilepic" text;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "registration_certificate" text;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "aadhar_card" text;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "pan_card" text;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "appointment_letter" text;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "10_document" text;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "12_document" text;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "bhms_document" text;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "md_document" text;